name: cypress-run-parallel
on: [push]

jobs:

  # cypress-run-1:
  #   environment: dev
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: Checkout 🛎
  #       uses: actions/checkout@v3

  #     - name: Cypress run 🚀
  #       uses: cypress-io/github-action@v3
  #       with:
  #         command: npm run run-1

  #     - name: Archive code coverage results
  #       if: always()
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: allure-results
  #         path: ./allure-results/

  cypress-run-2:
    environment: dev
    runs-on: ubuntu-20.04
    outputs:
      output1: ${{ steps.status_job.outputs.test }}
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Cypress run 🚀
        uses: cypress-io/github-action@v3
        with:
          command: npm run run-2

      - name: Archive code coverage results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: ./allure-results/

      - id: status_job
        run: echo "test=${{job.status}}" >> $GITHUB_OUTPUT

  cypress-run-3:
    environment: dev
    runs-on: ubuntu-20.04
    outputs:
      output1: ${{ steps.status_job.outputs.test }}
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Cypress run 🚀
        uses: cypress-io/github-action@v3
        with:
          command: npm run run-3

      - name: Archive code coverage results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: ./allure-results/

      - id: status_job
        run: echo "test=${{job.status}}" >> $GITHUB_OUTPUT

  generate-report:
    if: always()
    needs: [cypress-run-2, cypress-run-3]
    runs-on: ubuntu-latest
    steps:
      - name: Status Job
        shell: bash
        # if: jobs.cypress-run-2 
        run : |
          echo "somente 3 job: ${{(needs.cypress-run-2.outputs.output1 == 'success' && needs.cypress-run-3.outputs.output1 == 'success') && 'success' || 'failure'}}"

      # - name: job2 
      #   if: jobs.cypress-run-2
      #   run : |
      #     echo "somente 1 job: ${{jobs.cypress-run-2}}"
      #   run: |
      #     echo "status_test: ${{ env.TEST_STATUS }}"
      #     echo "status: ${{ job.status }}"

      #     echo "-------------------------"
      #     echo "get status by jobs :"
      #     echo cypress_2:${{needs.cypress-run-2.conclusion}}
      #     echo cypress_3:${{needs.cypress-run-3.conclusion}}

      #     echo "-------------------------"
      #     echo "fake ternary :"
      #     echo "${{needs.cypress-run-2.conclusion == 'success' && 'success' || 'failure' }}"
      #     echo "${{needs.cypress-run-2.conclusion && needs.cypress-run-3.conclusion == 'success' && 'success' || 'failure' }}"
          
      #     echo only expression to return true or false
      #     echo "${{(needs.cypress-run-2.conclusion && needs.cypress-run-3.conclusion)}}"
      # - name: Download all workflow run artifacts
      #   uses: actions/download-artifact@v3
      # - name: Deploy to GitHub Pages
      #         id: deployment
      #         uses: actions/deploy-pages@v1
      # - name: Checkout repository gh-pages
      #   uses: actions/checkout@v3
      #   continue-on-error: true
      #   with:
      #     ref: gh-pages
      #     path: gh-pages

      # - name: Generate allure report
      #   uses: simple-elf/allure-report-action@master
      #   id: allure-report
      #   with:
      #     allure_results: allure-results
      #     gh_pages: gh-pages
      #     allure_report: allure-report
      #     allure_history: allure-history

      # - name: Deploy report to Github Pages
      #   if: always()
      #   uses: peaceiris/actions-gh-pages@v2
      #   env:
      #     PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     PUBLISH_BRANCH: gh-pages
      #     PUBLISH_DIR: allure-history
