name: MATRIZ

on: [push]

jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  generate-report:
    needs: test
    runs-on: ubuntu-latest
    name: gerando relatorio
    steps:
      - name: escrevendo console
        run: echo "Gerando relatorio de execução"
    
  notify-report:
    needs: generate-report
    runs-on: ubuntu-latest
    name: notificando relatorio no slack
    steps:
      - name: escrevendo console
        run: echo "Gerando relatorio de execução"
