name: MATRIZ

on: [push]

jobs:

# cypress run
  cypress-run: 
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: diretorio 1
        run: echo pwd

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          record: true
          containers: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: diretorio 2
        run: echo pwd

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: ./allure-results

# generate-report
  generate-report:
    if: always()
    needs: cypress-run
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: allure-results
        
      - name: Generate allure report
        run: echo "Gerando relatorio de execução"

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

# notify-report
  notify-report:
    if: always()
    needs: generate-report
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        run: echo "Notificando relatorio no slack"
