name: MATRIZ

on: [push]

env:
  DAY_OF_WEEK: ${{ secrets.CONTAINERS }}

jobs:
  cypress-run: 
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        if: ${{env.DAY_OF_WEEK == '[1]'}}

      - name: Cypress run
        if: success()
        uses: cypress-io/github-action@v4
        with:
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cypress-run-parallel-2: 
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        if: ${{env.DAY_OF_WEEK == '[1, 2]'}}

      - name: Cypress run
        if: success()
        uses: cypress-io/github-action@v4
        with:
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cypress-run-parallel-3: 
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        if: ${{env.DAY_OF_WEEK == '[1, 2, 3]'}}

      - name: Cypress run
        if: success()
        uses: cypress-io/github-action@v4
        with:
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  # generate-report:
  #   if: ${{ always() }}
  #   needs: cypress-run
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Generate allure report
  #       run: echo "Gerando relatorio de execução"
    
  # notify-report:
  #   if: ${{ always() }}
  #   needs: generate-report
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Slack Notification
  #       run: echo "Notificando relatorio no slack"
